name: Build and Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build React app
              run: npm run build

            - name: Build Electron app
              run: npm run transpile:electron

            - name: Build and Release
              uses: electron-userland/electron-builder-action@v1
              with:
                  github_token: ${{ secrets.github_token }}
                  release: true
                  publish: always
                  config: electron-builder.yml
